export * from './arrow-right.icon';
export * from './chevron-right.icon';
export * from './clock.icon';
export * from './mortarboard.icon';
export * from './movie.icon';
export * from './next.icon';
export * from './paint.icon';
export * from "./pause.icon"
export * from './play.icon';
export * from './previous.icon';